// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gmrfICMEM
List gmrfICMEM(const arma::mat& y, const arma::ivec& x_int, const arma::sp_mat& Adj, const arma::mat& mu_int, const arma::cube& sigma_int, const arma::vec& alpha, const double& beta, const bool& PX, const int& maxIter_ICM, const int& maxIter);
RcppExport SEXP _SC_MEB_gmrfICMEM(SEXP ySEXP, SEXP x_intSEXP, SEXP AdjSEXP, SEXP mu_intSEXP, SEXP sigma_intSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP PXSEXP, SEXP maxIter_ICMSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type x_int(x_intSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Adj(AdjSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu_int(mu_intSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type sigma_int(sigma_intSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type PX(PXSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter_ICM(maxIter_ICMSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(gmrfICMEM(y, x_int, Adj, mu_int, sigma_int, alpha, beta, PX, maxIter_ICM, maxIter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SC_MEB_gmrfICMEM", (DL_FUNC) &_SC_MEB_gmrfICMEM, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_SC_MEB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
