# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmrfICMEM <- function(y, x_int, Adj, mu_int, sigma_int, alpha, beta, PX, maxIter_ICM, maxIter) {
    .Call(`_SC_MEB_gmrfICMEM`, y, x_int, Adj, mu_int, sigma_int, alpha, beta, PX, maxIter_ICM, maxIter)
}

